export const metadata = {
  title: "Dashboard",
  description: "Generated by create test next app",
};

export default function Layout({ children, users, revenue }) {
  return (
    <div>
      <div>{users}</div>
      <div>{children}</div>
      <div>{revenue}</div>
    </div>
  );
}
